# DoRun custom commands.
# Lookup order:
# 1. Command.conf next to DoRun.exe
# 2. %APPDATA%\DoRun\Command.conf
#
# Format:
# name:command_line:working_directory:show_window:priority_class

notepad:notepad.exe
cmd:"cmd.exe /k"
