# DoRun runtime configuration.
# Lookup order:
# 1. DoRun.toml next to DoRun.exe
# 2. %APPDATA%\DoRun\DoRun.toml

HOTKEY_MODIFIERS = 1
HOTKEY_VK = 32

DIR = [
    "C:\\Windows\\System32",
    "C:\\Program Files",
    "C:\\Program Files (x86)"
]
